/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as NewJobRouteImport } from './routes/new-job'
import { Route as ProcessingRouteImport } from './routes/processing'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as BrowseIndexRouteImport } from './routes/browse.index'
import { Route as BrowseChamberRouteImport } from './routes/browse.$chamber'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as RulingDocIdRouteImport } from './routes/ruling.$docId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NewJobRoute = NewJobRouteImport.update({
  id: '/new-job',
  path: '/new-job',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingRoute = ProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseIndexRoute = BrowseIndexRouteImport.update({
  id: '/browse/',
  path: '/browse/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseChamberRoute = BrowseChamberRouteImport.update({
  id: '/browse/$chamber',
  path: '/browse/$chamber',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const RulingDocIdRoute = RulingDocIdRouteImport.update({
  id: '/ruling/$docId',
  path: '/ruling/$docId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/new-job': typeof NewJobRoute
  '/processing': typeof ProcessingRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/browse/$chamber': typeof BrowseChamberRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/ruling/$docId': typeof RulingDocIdRoute
  '/browse/': typeof BrowseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/new-job': typeof NewJobRoute
  '/processing': typeof ProcessingRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/browse/$chamber': typeof BrowseChamberRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/ruling/$docId': typeof RulingDocIdRoute
  '/browse': typeof BrowseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/new-job': typeof NewJobRoute
  '/processing': typeof ProcessingRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/browse/$chamber': typeof BrowseChamberRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/ruling/$docId': typeof RulingDocIdRoute
  '/browse/': typeof BrowseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/billing'
    | '/dashboard'
    | '/new-job'
    | '/processing'
    | '/results'
    | '/settings'
    | '/browse/$chamber'
    | '/cases/$caseId'
    | '/ruling/$docId'
    | '/browse/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/billing'
    | '/dashboard'
    | '/new-job'
    | '/processing'
    | '/results'
    | '/settings'
    | '/browse/$chamber'
    | '/cases/$caseId'
    | '/ruling/$docId'
    | '/browse'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/billing'
    | '/dashboard'
    | '/new-job'
    | '/processing'
    | '/results'
    | '/settings'
    | '/browse/$chamber'
    | '/cases/$caseId'
    | '/ruling/$docId'
    | '/browse/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BillingRoute: typeof BillingRoute
  DashboardRoute: typeof DashboardRoute
  NewJobRoute: typeof NewJobRoute
  ProcessingRoute: typeof ProcessingRoute
  ResultsRoute: typeof ResultsRoute
  SettingsRoute: typeof SettingsRoute
  BrowseChamberRoute: typeof BrowseChamberRoute
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  RulingDocIdRoute: typeof RulingDocIdRoute
  BrowseIndexRoute: typeof BrowseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-job': {
      id: '/new-job'
      path: '/new-job'
      fullPath: '/new-job'
      preLoaderRoute: typeof NewJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/': {
      id: '/browse/'
      path: '/browse'
      fullPath: '/browse/'
      preLoaderRoute: typeof BrowseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$chamber': {
      id: '/browse/$chamber'
      path: '/browse/$chamber'
      fullPath: '/browse/$chamber'
      preLoaderRoute: typeof BrowseChamberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ruling/$docId': {
      id: '/ruling/$docId'
      path: '/ruling/$docId'
      fullPath: '/ruling/$docId'
      preLoaderRoute: typeof RulingDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BillingRoute: BillingRoute,
  DashboardRoute: DashboardRoute,
  NewJobRoute: NewJobRoute,
  ProcessingRoute: ProcessingRoute,
  ResultsRoute: ResultsRoute,
  SettingsRoute: SettingsRoute,
  BrowseChamberRoute: BrowseChamberRoute,
  CasesCaseIdRoute: CasesCaseIdRoute,
  RulingDocIdRoute: RulingDocIdRoute,
  BrowseIndexRoute: BrowseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
